// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swbeqefyudjryxwmhuvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3YmVxZWZ5dWRqcnl4d21odXZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MTU5OTMsImV4cCI6MjA2NzI5MTk5M30.o6wcq1C7YJH6k2Uc0rGIxEwpUe8wYLUZXx0h7Ott-yo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});